### PR TITLE
test  cases typo  fixed &  missing PHPDocs added.

### PR DESCRIPTION
**Pull request by MrWasimAbbasi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature? | ❌
| Breaks BC?    | ❌
| Fixed issues  | Typo fixes and missing PHPDoc added

### CODE REVIEW

**Comment by Tigrov** [comment]
Thanks for the PR, but the changes do not seem to make sense.

See https://github.com/yiisoft/docs/blob/master/010-code-style.md#comments

_Method comment is necessary except it adds nothing to what method name and signature already has._

**Comment by vjik** [comment]
It's make sense for exceptions, that need to catch in code, that usage it method.

**Comment by Tigrov** [comment]
> It's make sense for exceptions, that need to catch in code, that usage it method.

Then when possible and reasonably it is better to add them to interfaces.

**Review by samdark — CHANGES_REQUESTED** [review]

**Comment by samdark** [comment]
Closing since we're not going to apply the pull request. Thanks for submitting it anyway.

**Pull request closed without merging**
