### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by FabrizioCaldarelli**
db-mysql package tests are fully fixed.

It can be checked using at this time this PR : https://github.com/yiisoft/db/pull/44

### CODE REVIEW

**Comment by FabrizioCaldarelli** [comment]
How can I change the code to pass travis build?

**Comment by samdark** [comment]
That is weird error. Doesn't seem to be code-related.

**Comment by machour** [comment]
Add `mysql_upgrade` to the .travis.yml file, here's an example: https://github.com/yiisoft/db/blob/master/.travis.yml#L74

**Comment by samdark** [comment]
Helped. Thanks, @machour

**Comment by FabrizioCaldarelli** [comment]
To fix Travis test is needed to publish my PR on db package (related issue is here: https://github.com/yiisoft/db/pull/48/files#diff-605b1b829c7a2ab3747175bc34ff7b39).

https://github.com/yiisoft/db/pull/48

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
